#############################################################################
# Makefile for building: DataClassificationProject
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  DataClassificationProject.pro
# Template: app
# Command: T:\Qt5.14.2_SetUpAddress\5.14.2\mingw73_64\bin\qmake.exe -o Makefile DataClassificationProject.pro -spec win32-g++ "CONFIG+=release"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = T:\Qt5.14.2_SetUpAddress\5.14.2\mingw73_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = T:\Qt5.14.2_SetUpAddress\5.14.2\mingw73_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = T:\Qt5.14.2_SetUpAddress\5.14.2\mingw73_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: DataClassificationProject.pro T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/win32-g++/qmake.conf T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/spec_pre.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/qdevice.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/device_config.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/common/sanitize.conf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/common/gcc-base.conf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/common/g++-base.conf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/common/angle.conf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/common/windows-vulkan.conf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/common/g++-win32.conf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/common/windows-desktop.conf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/qconfig.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3drender.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axbase.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axserver.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_charts.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_charts_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_core.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_core_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_datavisualization.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_dbus.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designer.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gui.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_help.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_help_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_location.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_location_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_network.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_network_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_networkauth.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_nfc.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_opengl.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioning.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_purchasing.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qml.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3d.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3drender.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_repparser.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_script.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_script_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scripttools.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scxml.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sensors.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialport.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sql.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_svg.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_testlib.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uitools.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_websockets.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_widgets.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_winextras.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xml.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_zlib_private.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/qt_functions.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/qt_config.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/win32-g++/qmake.conf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/exclusive_builds.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/toolchain.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/default_pre.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/win32/default_pre.prf \
		excel/QXlsx.pri \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/resolve_config.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/exclusive_builds_post.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/default_post.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/precompile_header.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/warn_on.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/qt.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/resources_functions.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/resources.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/moc.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/win32/opengl.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/uic.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/qmake_use.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/file_copies.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/win32/windows.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/testcase_targets.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/exceptions.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/yacc.prf \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/lex.prf \
		DataClassificationProject.pro \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/lib/Qt5WinExtras.prl \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/lib/Qt5Widgets.prl \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/lib/Qt5Gui.prl \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/lib/Qt5Sql.prl \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/lib/Qt5Core.prl \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/lib/qtmain.prl \
		T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/build_pass.prf \
		Resource.qrc
	$(QMAKE) -o Makefile DataClassificationProject.pro -spec win32-g++ "CONFIG+=release"
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/spec_pre.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/qdevice.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/device_config.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/common/sanitize.conf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/common/gcc-base.conf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/common/g++-base.conf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/common/angle.conf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/common/windows-vulkan.conf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/common/g++-win32.conf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/common/windows-desktop.conf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/qconfig.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3drender.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axbase.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axserver.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_charts.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_charts_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_core.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_core_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_datavisualization.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_dbus.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designer.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gui.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_help.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_help_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_location.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_location_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_network.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_network_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_networkauth.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_networkauth_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_nfc.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_opengl.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioning.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_purchasing.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_purchasing_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qml.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlmodels.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3d.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3d_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3drender.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3drender_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3dutils.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_repparser.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_script.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_script_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scripttools.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scripttools_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scxml.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sensors.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialport.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sql.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_svg.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_testlib.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uitools.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_websockets.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_widgets.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_winextras.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xml.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/modules/qt_lib_zlib_private.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/qt_functions.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/qt_config.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/win32-g++/qmake.conf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/spec_post.prf:
.qmake.stash:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/exclusive_builds.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/toolchain.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/default_pre.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/win32/default_pre.prf:
excel/QXlsx.pri:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/resolve_config.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/exclusive_builds_post.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/default_post.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/precompile_header.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/warn_on.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/qt.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/resources_functions.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/resources.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/moc.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/win32/opengl.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/uic.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/qmake_use.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/file_copies.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/win32/windows.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/testcase_targets.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/exceptions.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/yacc.prf:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/lex.prf:
DataClassificationProject.pro:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/lib/Qt5WinExtras.prl:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/lib/Qt5Widgets.prl:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/lib/Qt5Gui.prl:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/lib/Qt5Sql.prl:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/lib/Qt5Core.prl:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/lib/qtmain.prl:
T:/Qt5.14.2_SetUpAddress/5.14.2/mingw73_64/mkspecs/features/build_pass.prf:
Resource.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile DataClassificationProject.pro -spec win32-g++ "CONFIG+=release"

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
